name: task
description: Task feature package for TODO App
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
  category:
  path_provider: ^2.1.1
  uuid: ^4.5.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  isar_plus: ^1.2.0
  isar_plus_flutter_libs: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
