name: todo_app
description: TODO App with Clean Architecture
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core:
  task:
  category:
  settings:
  flutter_bloc: ^9.0.0
  get_it: ^9.0.0
  go_router: ^17.0.1
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.4
  uuid: ^4.5.1
  lucide_icons: ^0.257.0
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
