name: category
description: Category domain package for TODO app
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Internal packages
  core:

  # Database
  isar_plus: ^1.2.0
  isar_plus_flutter_libs: ^1.2.0
  path_provider: ^2.1.1

  # Utils
  uuid: ^4.5.1

  # State management
  flutter_bloc: ^9.0.0

  # Code generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mocktail: ^1.0.0
  bloc_test: ^10.0.0

  # Code generation
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.9.0

  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
